name: erc
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy=1.21.0
  - torch
  - torchvision
  - absl-py
  - pyparsing
  - pillow=6.1
  - mujoco=2.3.0
  - mujoco-py=2.1.2.14
  - pip:
    - termcolor
    - mujoco
    - git+git://github.com/deepmind/dm_control.git
    - git+git://github.com/1nadequacy/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - torchvision
    - scikit-image
    - pynvml
    - opencv-python
    - plotly
    - torchvision
    - kornia
    - tqdm